server:
  port: 8080
  #项目名指定为shiro
  servlet:
    context-path: /shiro
spring:
  application:
    name: shiro

  #视图变成  / 与jsp
  mvc:
    view:
      prefix: /
      suffix: .jsp


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account?characterEncoding=UTF-8
    username: root
    password: root

mybatis:
  type-aliases-package: com.cuisf.entity
  mapper-locations: classpath:com/cuisf/mapper/*.xml



